version: '3.8'

services:
  server:
    image: fx-server
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - db

  dashboard:
    image: elsaworkflows/elsa-dashboard
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Elsa dashboard URL.
      ELSA__SERVER__BASEURL: http://localhost:5010
      # Elsa server URL, externally available.
      ELSA__SERVER__BASEADDRESS: http://localhost:5000
    ports:
      - '5010:80'

  web:
    image: fx-web
    build:
      context: .
      dockerfile: ./Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Domain: Server=db;Port=3306;Database=domain;User=root;Password=dev;
    ports:
      - '5100:80'
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: dev
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'

  smtp:
    image: rnwood/smtp4dev
    ports:
      - '25:25'
      - '2525:80'
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  mariadb-data:
  smtp4dev-data:
