version: '3.8'

services:
  # http://localhost:5100
  web:
    image: fx-web
    build:
      context: .
      dockerfile: ./Web/Dockerfile
    ports:
      - '5100:80'
    restart: on-failure
    depends_on:
      - db
      - mq

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: dev
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # Postgres management UI.
  # http://localhost:8080 with postgres/dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # http://localhost:2525
  smtp:
    image: rnwood/smtp4dev
    ports:
      - '25:25'
      - '2525:80'
    volumes:
      - smtp4dev-data:/smtp4dev

  mt:
    image: fx-mt
    build:
      context: .
      dockerfile: ./MT.Backend/Dockerfile
    restart: on-failure
    depends_on:
      - db
      - postgres
      - mq

  # http://localhost:15672 with guest/guest
  mq:
    image: masstransit/rabbitmq:3.8 # latest is broken (web UI)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mariadb-data:
  smtp4dev-data:
  postgres-data:
  rabbitmq-data:
